# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderLinuxbox < Formula
  desc "Terraform provider for managing Linux machines"
  homepage "https://github.com/draganm/terraform-provider-linuxbox"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/draganm/terraform-provider-linuxbox/releases/download/v#{version}/terraform-provider-linuxbox-darwin_amd64"
    sha256 "22c0ff73b7ea8988f7c949f5084aae22e40207e9a083152425211f8a75152949"
  end
  
  depends_on "terraform"

  def install
    bin.install "terraform-provider-linuxbox-darwin_amd64" => "terraform-provider-linuxbox_v#{version}"
  end

  def caveats; <<~EOS
    After installation, you must symlink the provider into Terraform's plugins directory.
    Symlinking is necessary because Homebrew is sandboxed and cannot write to your home directory.
    
    # Make the plugins directory if not present
    mkdir -p ~/.terraform.d/plugins/
    
    # Remove any old unversioned plugins (if applicable)
    rm -f  ~/.terraform.d/plugins/terraform-provider-linuxbox
    
    # Symlink the provider to your home dir. If Homebrew is installing somewhere other than /usr/local/Cellar, update the path as well.
    ln -sf /usr/local/Cellar/terraform-provider-linuxbox/#{version}/bin/terraform-provider-linuxbox_v#{version} ~/.terraform.d/plugins/terraform-provider-linuxbox_v#{version}
  EOS
  end

  test do
    # Running bin directly gives error, exit code 1
    system "#{bin}/terraform-provider-linuxbox_v#{version}", "-h"
  end
end
